#include <cstdlib>
#include <ios>
#include <iostream>
#include <cassert>
#include <iomanip>
#include <verilated.h>

const std::string ANSI_RESET    = "\033[0m";
const std::string ANSI_RED      = "\033[31m";   // red fg
const std::string ANSI_GREEN    = "\033[32m";   // green fg
const std::string ANSI_YELLOW   = "\033[33m";   // yellow fg
const std::string ANSI_B_RED    = "\033[1;31m"; // bold red
const std::string ANSI_B_GREEN  = "\033[1;32m"; // bold red

// NOTE: Function prototype is generated by Verilator
// like `extern void ecall_break(type...)`
// WARN: param type must match
extern "C" void 
call_ebreak(uint32_t pc, uint32_t a0reg) {
  std::cout << (a0reg ? 
      (ANSI_B_RED + std::string("Hit BAD trap" + ANSI_RESET)) : 
      (ANSI_B_GREEN + std::string("Hit GOOD trap" + ANSI_RESET)) )
    << " at pc = 0x" << std::hex << pc 
    << " with a0 = 0x" << std::hex << a0reg << std::endl;
  if (a0reg) {
    vl_fatal(__FILE__, __LINE__, "EcallBox:call_ebreak", "ebreak with nonzero a10");
  } else {
    vl_finish(__FILE__, __LINE__, "EcallBox:call_ebreak");
  }
}
